# Generated by Django 5.2.7 on 2025-12-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loginverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_sent_at',
        ),
        migrations.DeleteModel(
            name='LoginVerification',
        ),
    ]
