# Generated by Django 5.2.7 on 2026-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the unit used for this purchase', null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit (carton, packet, piece)', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the unit used for this purchase order', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit (carton, packet, piece)', max_length=50),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the unit used for this retail sale', null=True),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit sold', max_length=50),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the unit used for this sale order', null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit (carton, packet, piece)', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the unit used for this transfer', null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit (carton, packet, piece)', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
