# Generated by Django 5.2.7 on 2026-06-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseitem_base_quantity_purchaseitem_unit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_balance_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Customer's balance at the time of sale", max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for walk-in customers', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone for walk-in customers', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.productunit'),
        ),
    ]
