# Generated by Django 5.2.7 on 2026-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_saleitem_unit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='held_until',
            field=models.DateTimeField(blank=True, help_text='When the hold expires', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Reason for putting sale on hold', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When the hold was released', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20),
        ),
    ]
